
name: Unzip File

on: push

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Unzip file
      run: |
        sudo apt-get install unzip
        unzip <your-zip-file-name>.zip
        rm <your-zip-file-name>.zip
